export const ListBook = [
  {
    id: 1,
    title: "Halloween Candy",
    author: "Horror Storys",
    category: "Horror",
    rating: 4.2,
    sinopsis: "A spooky Halloween story.",
    is_free: true,
    views: 1200,
    img: require("../assets/books/Halloween_candy.png"),
  },
  {
    id: 2,
    title: "Hantu Durian",
    author: "Unknown",
    category: "Horror",
    rating: 4.0,
    sinopsis: "Kisah seram tentang hantu durian.",
    is_free: true,
    views: 980,
    img: require("../assets/books/Hantu_durian.png"),
  },
  {
    id: 3,
    title: "Hikayat Hang Tuah",
    author: "Unknown",
    category: "Classic",
    rating: 4.8,
    sinopsis: "Hikayat pahlawan Melayu legendaris.",
    is_free: false,
    views: 3400,
    img: require("../assets/books/Hikayat_hang_tuah.png"),
  },
  {
    id: 4,
    title: "Kancil dan Buaya",
    author: "Unknown",
    category: "Fable",
    rating: 4.3,
    sinopsis: "Kisah si kancil yang cerdik.",
    is_free: true,
    views: 870,
    img: require("../assets/books/Kancil_dan_buaya.png"),
  },
  {
    id: 5,
    title: "Kisah Konyol",
    author: "Unknown",
    category: "Comedy",
    rating: 4.1,
    sinopsis: "Kumpulan kisah lucu.",
    is_free: true,
    views: 650,
    img: require("../assets/books/Kisah_konyol.png"),
  },
  {
    id: 6,
    title: "Lutung Kasarung",
    author: "Unknown",
    category: "Folklore",
    rating: 4.5,
    sinopsis: "Legenda Sunda tentang Lutung Kasarung.",
    is_free: false,
    views: 2100,
    img: require("../assets/books/Lutung_kasarung.png"),
  },
  {
    id: 7,
    title: "Malin Kundang",
    author: "Unknown",
    category: "Folklore",
    rating: 4.6,
    sinopsis: "Legenda anak durhaka dari Sumbar.",
    is_free: false,
    views: 2800,
    img: require("../assets/books/Malin_kundang.png"),
  },
  {
    id: 8,
    title: "Putri Salju",
    author: "Brothers Grimm",
    category: "Fairytale",
    rating: 4.4,
    sinopsis: "Kisah putri salju dan penyihir jahat.",
    is_free: true,
    views: 1500,
    img: require("../assets/books/Putri_salju.jpg"),
  },
  {
    id: 9,
    title: "Raisa",
    author: "Unknown",
    category: "Music",
    rating: 4.7,
    sinopsis: "Kisah tentang Raisa.",
    is_free: false,
    views: 3100,
    img: require("../assets/books/Raisa.jpg"),
  },
  {
    id: 10,
    title: "Seorang Lelaki dan Kucingnya",
    author: "Unknown",
    category: "Fiction",
    rating: 4.3,
    sinopsis: "Kisah lelaki dan kucing kesayangannya.",
    is_free: true,
    views: 760,
    img: require("../assets/books/Seorang_lelaki_dan_kucingnya.jpeg"),
  },
  {
    id: 11,
    title: "Timun Mas",
    author: "Unknown",
    category: "Folklore",
    rating: 4.7,
    sinopsis: "Legenda Jawa tentang Timun Mas.",
    is_free: false,
    views: 2400,
    img: require("../assets/books/Timun_mas.png"),
  },
];